#!/usr/bin/env bash
#
# admin-core backup agent — processes requests from {{SPOOL}}/requests:
#   backup-db, backup-files, restore-db. Run by ROOT via cron once a minute.
#   The web admin only drops request files; this agent (root) does the
#   privileged work, and root never executes any application PHP.
#
# Generated by `php artisan admin-core:backup-agent-script`. Install (root):
#   php artisan admin-core:backup-agent-script > /usr/local/sbin/admin-core-backup-agent
#   chmod 700 /usr/local/sbin/admin-core-backup-agent
#   ( crontab -l 2>/dev/null; echo '* * * * * /usr/local/sbin/admin-core-backup-agent >> /var/log/admin-core-backup.log 2>&1' ) | crontab -
#
# DB-agnostic: pgsql / mysql / sqlite (from DB_CONNECTION in .env).
set -uo pipefail

SPOOL="{{SPOOL}}"; REQ="$SPOOL/requests"; DONE="$SPOOL/done"; STATUS="$SPOOL/status.json"
DBDIR="{{DB_DIR}}"; FILESDIR="{{FILES_DIR}}"
ENVFILE="{{ENV_FILE}}"; APP_BASE="{{APP_BASE}}"
PREFIX="{{PREFIX}}"; KEEP_DAYS="{{KEEP_DAYS}}"
FILES_PATHS="{{FILES_PATHS}}"        # space-separated, relative to APP_BASE
WEBGROUP="{{WEB_GROUP}}"             # group that may read backups (optional)

mkdir -p "$REQ" "$DONE" "$DBDIR" "$FILESDIR"
exec 9>"/var/lock/admin-core-backup.lock"; flock -n 9 || exit 0

val(){ grep -E "^$1=" "$ENVFILE" 2>/dev/null | head -1 | sed -E "s/^$1=//; s/^\"//; s/\"$//; s/^'//; s/'$//"; }
DB_CONNECTION="$(val DB_CONNECTION)"; DB_CONNECTION="${DB_CONNECTION:-pgsql}"
DBNAME="$(val DB_DATABASE)"; DBUSER="$(val DB_USERNAME)"; DBPASS="$(val DB_PASSWORD)"
DBHOST="$(val DB_HOST)"; DBHOST="${DBHOST:-127.0.0.1}"; DBPORT="$(val DB_PORT)"

write_status(){
  STATUS="$STATUS" python3 - "$1" "$2" "$3" "$4" <<'PY'
import json,sys,os,datetime
json.dump({"action":sys.argv[1],"file":sys.argv[2],"state":sys.argv[3],"message":sys.argv[4],
           "at":datetime.datetime.now().strftime("%F %T")}, open(os.environ["STATUS"],"w"), ensure_ascii=False)
PY
  chmod 664 "$STATUS" 2>/dev/null || true
  [ -n "$WEBGROUP" ] && chgrp "$WEBGROUP" "$STATUS" 2>/dev/null || true
}

dump_db(){  # $1 = output .sql.gz path
  case "$DB_CONNECTION" in
    pgsql)
      PGPASSWORD="$DBPASS" pg_dump --no-owner --no-privileges -h "$DBHOST" -p "${DBPORT:-5432}" -U "$DBUSER" "$DBNAME" | gzip -9 > "$1" ;;
    mysql|mariadb)
      mysqldump -h "$DBHOST" -P "${DBPORT:-3306}" -u "$DBUSER" -p"$DBPASS" "$DBNAME" | gzip -9 > "$1" ;;
    sqlite)
      gzip -9 -c "$DBNAME" > "$1" ;;   # DB_DATABASE is the sqlite file path
    *) return 1 ;;
  esac
}

restore_db(){  # $1 = .sql.gz path
  case "$DB_CONNECTION" in
    pgsql)
      export PGPASSWORD="$DBPASS"
      psql -h "$DBHOST" -p "${DBPORT:-5432}" -U "$DBUSER" -d "$DBNAME" -q -c "DROP OWNED BY $DBUSER CASCADE;" >/dev/null 2>&1
      gunzip -c "$1" | psql -h "$DBHOST" -p "${DBPORT:-5432}" -U "$DBUSER" -d "$DBNAME" -v ON_ERROR_STOP=1 -q ;;
    mysql|mariadb)
      gunzip -c "$1" | mysql -h "$DBHOST" -P "${DBPORT:-3306}" -u "$DBUSER" -p"$DBPASS" "$DBNAME" ;;
    sqlite)
      gunzip -c "$1" > "$DBNAME" ;;
    *) return 1 ;;
  esac
}

backup_files(){
  local ts="$1"
  ( cd "$APP_BASE" && tar -czf "$FILESDIR/uploads-$ts.tar.gz" $FILES_PATHS 2>/dev/null ) || true
  tar -czf "$FILESDIR/code-$ts.tar.gz" \
      --exclude='node_modules' --exclude='.output' --exclude='.nuxt' --exclude='vendor' \
      --exclude='.git' --exclude='storage/app' --exclude='storage/framework' \
      --exclude='storage/logs' --exclude='public/build' --exclude='public/storage' \
      -C "$(dirname "$APP_BASE")" "$(basename "$APP_BASE")" 2>/dev/null || true
}

prune(){ find "$DBDIR" -name "${PREFIX}-*.sql.gz" -type f -mtime +"$KEEP_DAYS" -delete 2>/dev/null
         find "$DBDIR" -name "pre-restore-*.sql.gz" -type f -mtime +"$KEEP_DAYS" -delete 2>/dev/null
         find "$FILESDIR" -name 'uploads-*.tar.gz' -type f -mtime +"$KEEP_DAYS" -delete 2>/dev/null
         find "$FILESDIR" -name 'code-*.tar.gz' -type f -mtime +"$KEEP_DAYS" -delete 2>/dev/null; }

shopt -s nullglob
for f in $(ls -1tr "$REQ"/*.json 2>/dev/null); do
  action=$(python3 -c "import json;print(json.load(open('$f')).get('action',''))" 2>/dev/null)
  reqfile=$(python3 -c "import json;print(json.load(open('$f')).get('file',''))" 2>/dev/null)
  base=$(basename "$reqfile")
  TS=$(date +%Y%m%d-%H%M%S)
  case "$action" in
    backup-db)
      write_status "$action" "" running "создаётся дамп БД"
      if dump_db "$DBDIR/${PREFIX}-$TS.sql.gz"; then prune; write_status "$action" "" ok "Бэкап БД создан"; else write_status "$action" "" error "Ошибка дампа БД ($DB_CONNECTION)"; fi ;;
    backup-files)
      write_status "$action" "" running "создаётся бэкап файлов"
      backup_files "$TS"; prune; write_status "$action" "" ok "Бэкап файлов создан" ;;
    restore-db)
      if [[ "$base" =~ ^(${PREFIX}|pre-restore)-[A-Za-z0-9._-]+\.sql\.gz$ ]] && [ -f "$DBDIR/$base" ]; then
        write_status "$action" "$base" running "восстановление из $base"
        dump_db "$DBDIR/pre-restore-$TS.sql.gz" || true
        if restore_db "$DBDIR/$base" >/dev/null 2>&1; then
          write_status "$action" "$base" ok "БД восстановлена из $base. Защитная копия: pre-restore-$TS.sql.gz"
        else
          write_status "$action" "$base" error "Ошибка восстановления из $base"
        fi
      else
        write_status "$action" "$base" error "Файл недопустим/не найден: $base"
      fi ;;
    *) write_status "$action" "$base" error "Неизвестное действие: $action" ;;
  esac
  mv "$f" "$DONE/" 2>/dev/null || rm -f "$f"
done
exit 0
