#!/usr/bin/env bash
#
# admin-core firewall-sync — reconciles ufw rules for SSH (port 22) with
# the `{{TABLE}}` table. Run by ROOT via cron once a minute. The web admin
# only writes rows into the table — it holds no privilege; all firewall
# work is isolated here, and root never executes any application PHP.
#
# Safety:
#   * the emergency addresses are always allowed → the list can never go
#     empty, lock-out is impossible even with an empty table;
#   * a FAILED read of the table never removes anything. The desired set is
#     unknown then, and «unknown» must not be read as «nothing»: bad DB
#     credentials in .env would otherwise wipe every allowed address on the
#     next cron tick. Rules are dropped only after the table was read;
#   * only well-formed IPv4 / IPv4-CIDR are accepted (garbage ignored);
#   * ONLY source rules for 22/tcp are managed, other ports untouched.
#
# Written for bash 3.2+ (no associative arrays) so it can be tested on the
# developer's Mac as well as run on the server.
#
# Generated by `php artisan admin-core:firewall-sync-script`.
# Install (as root):
#   php artisan admin-core:firewall-sync-script > /usr/local/sbin/admin-core-firewall-sync
#   chmod 700 /usr/local/sbin/admin-core-firewall-sync
#   ( crontab -l 2>/dev/null; echo '* * * * * /usr/local/sbin/admin-core-firewall-sync >> /var/log/admin-core-firewall.log 2>&1' ) | crontab -
#
set -uo pipefail

# One address (or CIDR block) per line — baked in at generation time.
EMERGENCY_IPS="{{EMERGENCY_IPS}}"
ENV_FILE="{{ENV_FILE}}"
TABLE="{{TABLE}}"
COMMENT="{{COMMENT}}"

log() { echo "$(date '+%F %T') $*"; }

# --- read DB access from .env (root can) ---
envval() { grep -E "^$1=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'"; }
DB_CONNECTION="$(envval DB_CONNECTION)"; DB_CONNECTION="${DB_CONNECTION:-pgsql}"
DB_DATABASE="$(envval DB_DATABASE)"
DB_USERNAME="$(envval DB_USERNAME)"
DB_PASSWORD="$(envval DB_PASSWORD)"
DB_HOST="$(envval DB_HOST)"; DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="$(envval DB_PORT)"

is_ipv4_or_cidr() {
    local v="$1" ip prefix n
    if [[ "$v" == */* ]]; then
        ip="${v%%/*}"; prefix="${v##*/}"
        [[ "$prefix" =~ ^[0-9]+$ ]] && (( prefix >= 0 && prefix <= 32 )) || return 1
    else
        ip="$v"
    fi
    local IFS='.'; read -r -a o <<< "$ip"
    [[ "${#o[@]}" -eq 4 ]] || return 1
    for n in "${o[@]}"; do
        [[ "$n" =~ ^[0-9]+$ ]] && (( n >= 0 && n <= 255 )) || return 1
    done
    return 0
}

# Membership test for the newline-separated lists used below.
contains() { printf '%s\n' "$1" | grep -Fxq -- "$2"; }

# --- pull allow-list rows, DB-agnostic ---
# Rows go to stdout, the client's own diagnostics to stderr; the exit code is
# the client's, so the caller can tell «table is empty» from «could not read».
fetch_rows() {
    case "$DB_CONNECTION" in
        pgsql)
            PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "${DB_PORT:-5432}" -U "$DB_USERNAME" -d "$DB_DATABASE" \
                -v ON_ERROR_STOP=1 -tAc "SELECT ip_address FROM ${TABLE}"
            ;;
        mysql|mariadb)
            mysql -h "$DB_HOST" -P "${DB_PORT:-3306}" -u "$DB_USERNAME" -p"$DB_PASSWORD" "$DB_DATABASE" \
                -N -B -e "SELECT ip_address FROM ${TABLE}"
            ;;
        sqlite)
            # DB_DATABASE is an absolute path for sqlite
            [[ -f "$DB_DATABASE" ]] || { echo "sqlite file not found: $DB_DATABASE" >&2; return 1; }
            sqlite3 "$DB_DATABASE" "SELECT ip_address FROM ${TABLE};"
            ;;
        *)
            echo "unsupported DB_CONNECTION='$DB_CONNECTION'" >&2
            return 1
            ;;
    esac
}

# --- desired set: emergency addresses + valid addresses from the table ---
want=""
while IFS= read -r ip; do
    ip="$(echo "$ip" | tr -d '[:space:]')"
    [[ -z "$ip" ]] && continue
    if is_ipv4_or_cidr "$ip"; then
        contains "$want" "$ip" || want="${want:+$want$'\n'}$ip"
    else
        log "SKIP invalid emergency address: '$ip'"
    fi
done <<< "$EMERGENCY_IPS"

if [[ -z "$want" ]]; then
    log "ERR no valid emergency address baked in — refusing to touch ufw"
    exit 1
fi

# --- add the emergency addresses first, before anything can go wrong ---
current_ssh_sources() {
    # `ufw status` format varies ("ALLOW" vs "ALLOW IN"), so don't bind to a
    # field index — find the IPv4/CIDR token in any column of the 22/tcp line.
    ufw status | awk '
        $1=="22/tcp" && /ALLOW/ {
            for (i=1; i<=NF; i++)
                if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(\/[0-9]+)?$/) { print $i; break }
        }'
}

have="$(current_ssh_sources)"

add_missing() {
    local list="$1" ip
    while IFS= read -r ip; do
        [[ -z "$ip" ]] && continue
        contains "$have" "$ip" && continue
        if ufw allow from "$ip" to any port 22 proto tcp comment "$COMMENT" >/dev/null 2>&1; then
            log "ADD ssh allow $ip"
            have="${have:+$have$'\n'}$ip"
        else
            log "ERR failed to add $ip"
        fi
    done <<< "$list"
}

add_missing "$want"

# --- read the table; a failure here stops the run before any removal ---
if [[ -z "$DB_DATABASE" ]]; then
    log "ERR no DB_DATABASE in $ENV_FILE — allow-list left as is (emergency addresses ensured)"
    exit 1
fi

# Keep the streams apart: a client may warn on stderr (locale, TLS, version
# skew) while succeeding, and those lines must never be mistaken for rows.
db_err="$(mktemp)"
rows="$(fetch_rows 2>"$db_err")"
rc=$?

if (( rc != 0 )); then
    log "ERR could not read ${TABLE} (${DB_CONNECTION}, exit ${rc}) — allow-list left as is (emergency addresses ensured)"
    log "ERR db said: $(tr '\n' ' ' < "$db_err" | cut -c1-300)"
    rm -f "$db_err"
    exit 1
fi
rm -f "$db_err"

while IFS= read -r ip; do
    ip="$(echo "$ip" | tr -d '[:space:]')"
    [[ -z "$ip" ]] && continue
    if is_ipv4_or_cidr "$ip"; then
        contains "$want" "$ip" || want="${want:+$want$'\n'}$ip"
    else
        log "SKIP invalid ip from db: '$ip'"
    fi
done <<< "$rows"

# --- the table was read: now the two sets can be reconciled ---
add_missing "$want"

while IFS= read -r ip; do
    [[ -z "$ip" ]] && continue
    contains "$want" "$ip" && continue
    if ufw delete allow from "$ip" to any port 22 proto tcp >/dev/null 2>&1; then
        log "DEL ssh allow $ip"
    else
        log "WARN could not delete $ip (rule may lack proto tcp)"
    fi
done <<< "$have"

exit 0
