#!/usr/bin/env bash
#
# admin-core firewall-sync — reconciles ufw rules for SSH (port 22) with
# the `{{TABLE}}` table. Run by ROOT via cron once a minute. The web admin
# only writes rows into the table — it holds no privilege; all firewall
# work is isolated here, and root never executes any application PHP.
#
# Safety:
#   * EMERGENCY_IP is always allowed → the list can never go empty,
#     lock-out is impossible even with an empty/broken table;
#   * only well-formed IPv4 / IPv4-CIDR are accepted (garbage ignored);
#   * ONLY source rules for 22/tcp are managed, other ports untouched.
#
# Generated by `php artisan admin-core:firewall-sync-script`.
# Install (as root):
#   php artisan admin-core:firewall-sync-script > /usr/local/sbin/admin-core-firewall-sync
#   chmod 700 /usr/local/sbin/admin-core-firewall-sync
#   ( crontab -l 2>/dev/null; echo '* * * * * /usr/local/sbin/admin-core-firewall-sync >> /var/log/admin-core-firewall.log 2>&1' ) | crontab -
#
set -uo pipefail

EMERGENCY_IP="{{EMERGENCY_IP}}"
ENV_FILE="{{ENV_FILE}}"
TABLE="{{TABLE}}"
COMMENT="{{COMMENT}}"

log() { echo "$(date '+%F %T') $*"; }

# --- read DB access from .env (root can) ---
envval() { grep -E "^$1=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'"; }
DB_CONNECTION="$(envval DB_CONNECTION)"; DB_CONNECTION="${DB_CONNECTION:-pgsql}"
DB_DATABASE="$(envval DB_DATABASE)"
DB_USERNAME="$(envval DB_USERNAME)"
DB_PASSWORD="$(envval DB_PASSWORD)"
DB_HOST="$(envval DB_HOST)"; DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="$(envval DB_PORT)"

is_ipv4_or_cidr() {
    local v="$1" ip prefix
    if [[ "$v" == */* ]]; then
        ip="${v%%/*}"; prefix="${v##*/}"
        [[ "$prefix" =~ ^[0-9]+$ ]] && (( prefix >= 0 && prefix <= 32 )) || return 1
    else
        ip="$v"
    fi
    local IFS='.'; read -r -a o <<< "$ip"
    [[ "${#o[@]}" -eq 4 ]] || return 1
    for n in "${o[@]}"; do
        [[ "$n" =~ ^[0-9]+$ ]] && (( n >= 0 && n <= 255 )) || return 1
    done
    return 0
}

# --- pull allow-list rows, DB-agnostic ---
fetch_rows() {
    case "$DB_CONNECTION" in
        pgsql)
            PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "${DB_PORT:-5432}" -U "$DB_USERNAME" -d "$DB_DATABASE" \
                -tAc "SELECT ip_address FROM ${TABLE}" 2>/dev/null
            ;;
        mysql|mariadb)
            mysql -h "$DB_HOST" -P "${DB_PORT:-3306}" -u "$DB_USERNAME" -p"$DB_PASSWORD" "$DB_DATABASE" \
                -N -B -e "SELECT ip_address FROM ${TABLE}" 2>/dev/null
            ;;
        sqlite)
            # DB_DATABASE is an absolute path for sqlite
            [[ -f "$DB_DATABASE" ]] && sqlite3 "$DB_DATABASE" "SELECT ip_address FROM ${TABLE};" 2>/dev/null
            ;;
        *)
            log "WARN: unsupported DB_CONNECTION='$DB_CONNECTION' — applying only EMERGENCY_IP"
            ;;
    esac
}

# --- desired set: emergency + valid addresses from DB ---
declare -A want
want["$EMERGENCY_IP"]=1

if [[ -n "$DB_DATABASE" ]]; then
    while IFS= read -r ip; do
        ip="$(echo "$ip" | tr -d '[:space:]')"
        [[ -z "$ip" ]] && continue
        if is_ipv4_or_cidr "$ip"; then want["$ip"]=1; else log "SKIP invalid ip from db: '$ip'"; fi
    done <<< "$(fetch_rows)"
else
    log "WARN: no DB_DATABASE in $ENV_FILE — applying only EMERGENCY_IP"
fi

# --- current source IPs for 22/tcp ---
# `ufw status` format varies ("ALLOW" vs "ALLOW IN"), so don't bind to a
# field index — find the IPv4/CIDR token in any column of the 22/tcp line.
declare -A have
while IFS= read -r line; do
    have["$line"]=1
done < <(ufw status | awk '
    $1=="22/tcp" && /ALLOW/ {
        for (i=1; i<=NF; i++)
            if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(\/[0-9]+)?$/) { print $i; break }
    }')

# --- add what is missing ---
for ip in "${!want[@]}"; do
    if [[ -z "${have[$ip]:-}" ]]; then
        if ufw allow from "$ip" to any port 22 proto tcp comment "$COMMENT" >/dev/null 2>&1; then
            log "ADD ssh allow $ip"
        else
            log "ERR failed to add $ip"
        fi
    fi
done

# --- remove what is extra (in ufw but not wanted) ---
for ip in "${!have[@]}"; do
    if [[ -z "${want[$ip]:-}" ]]; then
        if ufw delete allow from "$ip" to any port 22 proto tcp >/dev/null 2>&1; then
            log "DEL ssh allow $ip"
        else
            log "WARN could not delete $ip (rule may lack proto tcp)"
        fi
    fi
done

exit 0
